In [1]:
import pandas as pd

In [2]:
# df_acp = pd.read_csv('data/acp/train_data.csv', header=0) # reading the training dataset for acp
# df_acp_test = pd.read_csv('data/acp/test_data.csv', header=0) # reading the test dataset for acp


In [3]:
# df_amp = pd.read_csv('data/amp/all_data.csv', header=0) # reading the training dataset for amp
# df_amp_test = pd.read_csv('data/amp/all_data.csv', header=1) # reading the test dataset for amp

In [4]:
df_dna = pd.read_csv('data/dna_binding/train.csv', header=0) # reading the training dataset for dna
df_dna_test = pd.read_csv('data/dna_binding/test.csv', header=0) # reading the test dataset for dna


In [5]:
df_dna.head(2)

code                                           sequence  label  \
0  Q6A8L0  MSGHSKWATTKHKKAAIDAKRGKLFARLIKNIEVAARLGGGDPSGN...      1   
1  Q7V7T9  MIGWLQGQKVEAWQQGTRQGVVLACAGVGYEVQIAPRHLSEMEHGQ...      1   

                                              origin  
0  https://github.com/hfuulgb/PDB-Fusion/tree/mai...  
1  https://github.com/hfuulgb/PDB-Fusion/tree/mai...

In [6]:
# split sequences into single characters
df_dna_split = df_dna['sequence'].str.split(pat="", expand=True)

In [7]:
df_dna_split.sample(3)

0    1    2    3    4    5    6    7    8    9     ...  4903  4904  4905  \
4889         M    A    S    S    P    L    T    A    N  ...  None  None  None   
9026         Q    D    W    S    S    F    Q    N    K  ...  None  None  None   
2718         M    S    I    D    F    P    L    G    D  ...  None  None  None   

      4906  4907  4908  4909  4910  4911  4912  
4889  None  None  None  None  None  None  None  
9026  None  None  None  None  None  None  None  
2718  None  None  None  None  None  None  None  

[3 rows x 4913 columns]

In [8]:
df_dna_test_split = df_dna_test['sequence'].str.split(pat="", expand=True)

In [9]:
df3 = df_dna[['code']].join(df_dna_split)

In [10]:
df_dna_01 = df3.join(df_dna[['label']])

In [11]:
df_dna_01.head(3)

code 0  1  2  3  4  5  6  7  8  ...  4904  4905  4906  4907  4908  4909  \
0  Q6A8L0    M  S  G  H  S  K  W  A  ...  None  None  None  None  None  None   
1  Q7V7T9    M  I  G  W  L  Q  G  Q  ...  None  None  None  None  None  None   
2  Q9ZUP2    M  A  R  I  L  R  N  V  ...  None  None  None  None  None  None   

   4910  4911  4912 label  
0  None  None  None     1  
1  None  None  None     1  
2  None  None  None     1  

[3 rows x 4915 columns]

In [12]:
df_dna_01.shape

(14189, 4915)

In [13]:
# test dna
df4 = df_dna_test[['code']].join(df_dna_test_split)
df_dna_test_01 = df4.join(df_dna_test[['label']])
df_dna_test_01.head(3)

code 0  1  2  3  4  5  6  7  8  ...  5176  5177  5178  5179  5180  \
0  P27204|1    A  K  K  R  S  R  S  R  ...  None  None  None  None  None   
1  P53528|1    M  V  M  V  V  N  P  L  ...  None  None  None  None  None   
2  P52684|1    M  K  D  D  I  N  Q  E  ...  None  None  None  None  None   

   5181  5182  5183  5184 label  
0  None  None  None  None     1  
1  None  None  None  None     1  
2  None  None  None  None     1  

[3 rows x 5187 columns]

In [14]:
# df5 = df_dna_test.copy() ### [[pd.Series.str.len(['sequence'])]]
# df5['seq_length'] = df_dna_test['sequence'].str.len()
# print(df5.head(3))
# print(df5.loc[df5['seq_length'].idxmax()]['seq_length']) # length of longest sequence
# df5['seq_length'].idxmax() #['seq_length']
# df5.sort_values(by='seq_length', ascending=False, inplace=False).head(3)

In [15]:
letters = ['','A', 'B', 'C', 'D', 'E', 'F', 'G','H','I','J','K','L','M',
         'N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
letter_2num = { s: i for i, s in enumerate(letters) }

In [16]:
df_dna_01.columns[1: len(df_dna_01.columns)-1]

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912],
      dtype='object', length=4913)

`Encode protein sequences`

In [17]:
%%timeit
for column in df_dna_01.columns[1: len(df_dna_01.columns)-1]:
    df_dna_01[column] = df_dna_01[column].replace(letter_2num)

2.39 s ± 81.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
df_dna_01.to_csv('data/dna_binding/dna_train_file.csv')

In [19]:
df_dna_01.describe()

0             1             2             3             4  \
count  14189.0  14189.000000  14189.000000  14189.000000  14189.000000   
mean       0.0     12.973994     11.546409     12.558884     12.797801   
std        0.0      1.135561      7.110969      6.453527      6.468281   
min        0.0      1.000000      1.000000      1.000000      1.000000   
25%        0.0     13.000000      5.000000      7.000000      7.000000   
50%        0.0     13.000000     12.000000     12.000000     12.000000   
75%        0.0     13.000000     19.000000     18.000000     19.000000   
max        0.0     25.000000     25.000000     25.000000     25.000000   

                  5             6             7             8             9  \
count  14189.000000  14189.000000  14189.000000  14189.000000  14189.000000   
mean      12.528015     12.501656     12.427091     12.355416     12.174924   
std        6.517397      6.522970      6.522239      6.613055      6.622168   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        7.000000      7.000000      7.000000      7.000000      7.000000   
50%       12.000000     12.000000     12.000000     12.000000     12.000000   
75%       18.000000     18.000000     18.000000     18.000000     18.000000   
max       25.000000     25.000000     25.000000     25.000000     25.000000   

       ...  4904  4905  4906  4907  4908  4909  4910  4911  4912         label  
count  ...   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  14189.000000  
mean   ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      0.502431  
std    ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN      0.500012  
min    ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      0.000000  
25%    ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      0.000000  
50%    ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      1.000000  
75%    ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      1.000000  
max    ...  22.0  14.0   3.0  18.0  11.0  23.0  13.0  14.0   0.0      1.000000  

[8 rows x 4914 columns]

In [20]:
df_dna_02 = df_dna_01.fillna(0)

In [23]:
df_dna_02.sample(2)

code  0   1   2   3   4   5  6   7   8  ...  5176  5177  5178  5179  \
9940   Q32AV4  0  13  20  17  12   1  9   7  11  ...   0.0   0.0   0.0   0.0   
10181  Q5GT39  0  13  22   5  17  11  4  11  25  ...   0.0   0.0   0.0   0.0   

       5180  5181  5182  5183  5184  label  
9940    0.0   0.0   0.0   0.0   0.0      0  
10181   0.0   0.0   0.0   0.0   0.0      0  

[2 rows x 5187 columns]

In [24]:
y_train = df_dna_02['label'].values
X_train = df_dna_02.drop(columns=['code','label']).values

In [25]:
y_train

array([1, 1, 1, ..., 0, 0, 0])

In [26]:
X_train

array([[ 0., 13., 19., ...,  0.,  0.,  0.],
       [ 0., 13.,  9., ...,  0.,  0.,  0.],
       [ 0., 13.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0., 13.,  1., ...,  0.,  0.,  0.],
       [ 0., 13., 11., ...,  0.,  0.,  0.],
       [ 0., 13.,  7., ..., 20.,  8.,  0.]])

In [27]:
import numpy as np
#X_train[X_train == ''] = 0 # not needed anymore
X_train.astype(np.float64)

array([[ 0., 13., 19., ...,  0.,  0.,  0.],
       [ 0., 13.,  9., ...,  0.,  0.,  0.],
       [ 0., 13.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0., 13.,  1., ...,  0.,  0.,  0.],
       [ 0., 13., 11., ...,  0.,  0.,  0.],
       [ 0., 13.,  7., ..., 20.,  8.,  0.]])

In [28]:
# %%timeit
for column in df_dna_test_01.columns[1: len(df_dna_test_01.columns)-1]:
    df_dna_test_01[column] = df_dna_test_01[column].replace(letter_2num)

In [29]:
df_dna_test_01.to_csv('data/dna_binding/dna_test_file.csv')

In [30]:
df_dna_test_02 = df_dna_test_01.fillna(0)

df_dna_test_02.sample(2)

code  0   1   2   3   4   5   6   7   8  ...  5176  5177  5178  5179  \
829  P35201|1  0  13   4  25  13  11  12   7  12  ...   0.0   0.0   0.0   0.0   
811  Q12766|1  0  18  25   3  18   3  19  18  17  ...   0.0   0.0   0.0   0.0   

     5180  5181  5182  5183  5184  label  
829   0.0   0.0   0.0   0.0   0.0      1  
811   0.0   0.0   0.0   0.0   0.0      1  

[2 rows x 5187 columns]

In [31]:
y_test = df_dna_test_02['label'].values
X_test = df_dna_test_02.drop(columns=['code','label']).values

In [32]:
X_test.astype(np.float64)

array([[ 0.,  1., 11., ...,  0.,  0.,  0.],
       [ 0., 13., 22., ...,  0.,  0.,  0.],
       [ 0., 13., 11., ...,  0.,  0.,  0.],
       ...,
       [ 0., 13., 14., ...,  0.,  0.,  0.],
       [ 0., 13., 22., ...,  0.,  0.,  0.],
       [ 0., 13., 14., ...,  0.,  0.,  0.]])

In [39]:
df4 = None
df5 = None

In [40]:
#scale the features, applying MinMaxScaler

from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import GradientBoostingClassifier
scaler = MinMaxScaler() 

In [42]:

X_train = scaler.fit_transform(X_train) 

In [43]:
X_test

array([[ 0.,  1., 11., ...,  0.,  0.,  0.],
       [ 0., 13., 22., ...,  0.,  0.,  0.],
       [ 0., 13., 11., ...,  0.,  0.,  0.],
       ...,
       [ 0., 13., 14., ...,  0.,  0.,  0.],
       [ 0., 13., 22., ...,  0.,  0.,  0.],
       [ 0., 13., 14., ...,  0.,  0.,  0.]])

In [45]:
X_test = scaler.fit_transform(X_test) 

In [46]:
print(X_train.shape)
print(y_train.shape)


(14190, 5185)
(14190,)


In [47]:
%%time
gbt_model = GradientBoostingClassifier(random_state=42)
gbt_model.fit(X_train, y_train)

CPU times: user 2min 34s, sys: 166 ms, total: 2min 34s
Wall time: 2min 34s


GradientBoostingClassifier(random_state=42)

In [50]:
gbt_pred = gbt_model.predict(X_test)
# print(X_test.shape)

In [51]:
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score as accuracy,
    recall_score as recall,
    precision_score as precision,
    f1_score
)

print("accuracy:", accuracy(y_test, gbt_pred))
print("precision:", precision(y_test, gbt_pred))
print("recall:", recall(y_test, gbt_pred))
print("f1 score:", f1_score(y_test, gbt_pred))
print("confusion matrix:")
print(confusion_matrix(y_test, gbt_pred))

accuracy: 0.6320422535211268
precision: 0.603257328990228
recall: 0.803122289679098
f1 score: 0.6889880952380952
confusion matrix:
[[510 609]
 [227 926]]


In [55]:
%%time
from tpot import TPOTClassifier
tpot = TPOTClassifier(generations=10, 
                      population_size=16,
                      scoring='f1',
                      verbosity=2,
                      random_state=42)
tpot.fit(X_test, y_test)
print(f"Tpop score on test data: {tpot.score(X_test, y_test):.2f}")
tpot.export('acp_pipeline.py')

/home/chrisogonas/anaconda3/envs/py39_12/lib/python3.9/site-packages/tpot/builtins/__init__.py:36: UserWarning: Warning: optional dependency `torch` is not available. - skipping import of NN models.
  warnings.warn("Warning: optional dependency `torch` is not available. - skipping import of NN models.")


Optimization Progress:   0%|          | 0/176 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 0.6732841140041623

Generation 2 - Current best internal CV score: 0.6732841140041623

Generation 3 - Current best internal CV score: 0.6732841140041623

Generation 4 - Current best internal CV score: 0.6732841140041623


: 

: 

In [ ]:
!cat acp_pipeline.py #copy some of the code generated below